import os
import pandas as pd
from fastapi import FastAPI, HTTPException
import config

app = FastAPI(
    title="48-Hour Hyperlocal Forecast API",
    description="Serves the mathematically corrected 48-hour temperature forecast generated by the local KNN model.",
    version="1.0.0"
)

@app.get("/api/v1/forecast")
def get_forecast():
    """
    Returns the latest 48-hour forecast as a clean JSON array.
    """
    forecast_file = os.path.join(config.BASE_DIR, "forecast_48h.csv")
    
    if not os.path.exists(forecast_file):
        raise HTTPException(status_code=503, detail="Forecast data is not yet available. The background engine may still be processing.")
        
    try:
        # Read the auto-generated forecast CSV
        df = pd.read_csv(forecast_file)
        
        # Convert DataFrame to a list of dicts
        # Replace NaN/NaT with None for valid JSON serialization
        df = df.where(pd.notnull(df), None)
        data = df.to_dict(orient="records")
        
        return {
            "status": "success",
            "count": len(data),
            "forecast": data
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal server error parsing forecast data: {str(e)}")

@app.get("/api/v1/health")
def health_check():
    """Simple health check endpoint for AWS API Gateway / Load Balancers."""
    return {"status": "healthy"}

if __name__ == "__main__":
    import uvicorn
    # When run locally: python api.py
    uvicorn.run(app, host="0.0.0.0", port=8000)
